# Generated by Django 5.1.4 on 2025-01-20 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_admin_customuser_alter_chat_receiver_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Institution',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='name',
            new_name='institution_name',
        ),
    ]
