# Generated by Django 5.1.4 on 2025-01-20 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_admin_institution_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['attendance_date'], 'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendances'},
        ),
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['created_at'], 'verbose_name': 'Chat', 'verbose_name_plural': 'Chats'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['name'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['name'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['institution_name'], 'verbose_name': 'Institution', 'verbose_name_plural': 'Institutions'},
        ),
        migrations.AlterModelOptions(
            name='marks',
            options={'ordering': ['student__user__name'], 'verbose_name': 'Mark', 'verbose_name_plural': 'Marks'},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'ordering': ['user__name'], 'verbose_name': 'Parent', 'verbose_name_plural': 'Parents'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['roll_number'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='studentevaluation',
            options={'ordering': ['student'], 'verbose_name': 'Student Evaluation', 'verbose_name_plural': 'Student Evaluations'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['name'], 'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.RemoveField(
            model_name='class',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='password',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.AddField(
            model_name='class',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.institution'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.institution'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='Unknown Teacher', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='attendance',
            table='attendances',
        ),
        migrations.AlterModelTable(
            name='chat',
            table='chats',
        ),
        migrations.AlterModelTable(
            name='class',
            table='classes',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='custom_users',
        ),
        migrations.AlterModelTable(
            name='institution',
            table='institutions',
        ),
        migrations.AlterModelTable(
            name='marks',
            table='marks',
        ),
        migrations.AlterModelTable(
            name='parent',
            table='parents',
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
        migrations.AlterModelTable(
            name='studentevaluation',
            table='student_evaluations',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='subjects',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='teachers',
        ),
    ]
