# Generated by Django 5.1.4 on 2025-01-20 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_attendance_options_alter_chat_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentevaluation',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='institution',
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='chat',
            options={},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={},
        ),
        migrations.AlterModelOptions(
            name='marks',
            options={},
        ),
        migrations.RemoveField(
            model_name='chat',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='created_at',
        ),
        migrations.AddField(
            model_name='institution',
            name='institution_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='marks',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='marks',
            name='mark_percentage',
            field=models.FloatField(),
        ),
        migrations.AlterModelTable(
            name='attendance',
            table=None,
        ),
        migrations.AlterModelTable(
            name='chat',
            table=None,
        ),
        migrations.AlterModelTable(
            name='institution',
            table=None,
        ),
        migrations.AlterModelTable(
            name='marks',
            table=None,
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('roll_no', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.classes')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
        migrations.CreateModel(
            name='StudentEvaluations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('study_time_rating', models.FloatField()),
                ('sleep_time_rating', models.FloatField()),
                ('stress_handling_rating', models.FloatField()),
                ('homework_completion_rating', models.FloatField()),
                ('class_participation_rating', models.FloatField()),
                ('focus_rating', models.FloatField()),
                ('test_preparation_rating', models.FloatField()),
                ('class_difficulty_rating', models.FloatField()),
                ('parent_rating', models.FloatField()),
                ('teacher_rating', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.students')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsResponses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('student_response', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quizzes')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.students')),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.students'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.students'),
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.classes')),
            ],
        ),
        migrations.AddField(
            model_name='quizzes',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subjects'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subjects'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subjects'),
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.classes')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.institution')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('student_roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.students', to_field='roll_no')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
        migrations.AlterField(
            model_name='chat',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='main.users'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='main.users'),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='StudentEvaluation',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
