# Generated by Django 5.1.4 on 2025-01-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_users_remove_student_class_name_remove_parent_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='institution_id',
        ),
        migrations.AlterField(
            model_name='institution',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
