# Generated by Django 5.1.4 on 2025-02-01 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_chat_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='receiver_id',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='sender_id',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='classes',
            old_name='institution_id',
            new_name='institution',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='quizzes',
            old_name='class_id',
            new_name='class_obj',
        ),
        migrations.RenameField(
            model_name='quizzes',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='studentevaluations',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='class_id',
            new_name='class_obj',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='class_id',
            new_name='class_obj',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='name',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='student_roll_no',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='studentevaluations',
            name='focus_rating',
        ),
        migrations.RemoveField(
            model_name='studentevaluations',
            name='stress_handling_rating',
        ),
        migrations.RemoveField(
            model_name='students',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='name',
        ),
        migrations.AddField(
            model_name='classes',
            name='class_head',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classes',
            name='class_name',
            field=models.CharField(default='Default Class Name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classes',
            name='email',
            field=models.EmailField(default='default@domain.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classes',
            name='password',
            field=models.CharField(default='defaultpassword123', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classes',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parents',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.students', to_field='roll_no'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parents',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizzes',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.students'),
        ),
        migrations.AddField(
            model_name='students',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='email',
            field=models.EmailField(default='default@domain.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='password',
            field=models.CharField(default='defaultpassword123', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='subject_head',
            field=models.CharField(default='Default Subject Head', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='subject_name',
            field=models.CharField(default='Default Subject Name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='institution',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parents',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parents',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='correct_option',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='option_a',
            field=models.CharField(default='Option A', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='option_b',
            field=models.CharField(default='Option B', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='option_c',
            field=models.CharField(default='Option C', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='option_d',
            field=models.CharField(default='Option D', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='student_response',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='students',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='students',
            name='roll_no',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('class_head', 'Class Head'), ('subject_head', 'Subject Head'), ('student', 'Student'), ('parent', 'Parent')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
