# Generated by Django 5.1.4 on 2025-02-08 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_announcements_studymaterials'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterials',
            name='announcement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.announcements'),
        ),
        migrations.AlterField(
            model_name='studymaterials',
            name='file_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
