# Generated by Django 5.1.4 on 2025-02-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_studymaterials_announcement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterials',
            name='announcement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
