# Generated by Django 5.1.4 on 2025-02-08 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_studymaterials_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcements',
            name='subject',
        ),
    ]
