# Generated by Django 5.1.4 on 2025-02-09 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_announcements_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='student',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='student_response',
        ),
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_response', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quizzes')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.students')),
            ],
        ),
    ]
