# Generated by Django 5.1.4 on 2025-02-09 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_quizzes_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresponse',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='correct_option',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='option_a',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='option_b',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='option_c',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='option_d',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='question',
        ),
        migrations.CreateModel(
            name='QuizQuestions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.quizzes')),
            ],
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='question',
            field=models.ForeignKey(default='Default Question', on_delete=django.db.models.deletion.CASCADE, to='main.quizquestions'),
            preserve_default=False,
        ),
    ]
