# Generated by Django 5.1.4 on 2025-02-09 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_quizquestions_quiz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quizresponse',
            name='student',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='class_obj',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='subject',
        ),
        migrations.DeleteModel(
            name='QuizQuestions',
        ),
        migrations.DeleteModel(
            name='QuizResponse',
        ),
        migrations.DeleteModel(
            name='Quizzes',
        ),
    ]
