# Generated by Django 5.1.4 on 2025-02-11 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_quizquestions_quizresponse_quizzes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEvaluation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('study_time_rating', models.FloatField()),
                ('sleep_time_rating', models.FloatField()),
                ('homework_completion_rating', models.FloatField()),
                ('assignment_rating', models.FloatField()),
                ('attendance_percentage', models.FloatField()),
                ('marks_percentage', models.FloatField()),
                ('quiz_percentage', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.students')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subjects')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentEvaluations',
        ),
    ]
