# Generated by Django 5.1.4 on 2025-02-11 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_studentevaluation_delete_studentevaluations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresponse',
            name='question',
        ),
    ]
