# Generated by Django 5.1.4 on 2025-02-11 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_quizresponse_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresponse',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.quizquestions'),
            preserve_default=False,
        ),
    ]
