# Generated by Django 5.1.4 on 2025-02-11 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_quizresponse_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizResponse',
        ),
    ]
