# Generated by Django 5.1.4 on 2025-02-15 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_quizquestions_quizresponse_quizzes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.students'),
        ),
    ]
