# Generated by Django 5.1.4 on 2025-02-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_students_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentevaluation',
            name='assignment_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='attendance_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='homework_completion_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='marks_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='quiz_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='sleep_time_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='study_time_rating',
            field=models.FloatField(null=True),
        ),
    ]
