# Generated by Django 5.1.4 on 2025-02-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_studentevaluation_quiz_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentevaluation',
            old_name='homework_completion_rating',
            new_name='class_performance_rating',
        ),
    ]
