# Generated by Django 5.1.4 on 2025-02-23 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_rename_homework_completion_rating_studentevaluation_class_performance_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentevaluation',
            old_name='class_performance_rating',
            new_name='class_participation_rating',
        ),
    ]
