# Generated by Django 5.1.4 on 2025-02-23 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_rename_class_performance_rating_studentevaluation_class_participation_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentevaluation',
            old_name='assignment_rating',
            new_name='academic_activity_rating',
        ),
    ]
