# Generated by Django 5.1.6 on 2025-03-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_announcements_id_alter_attendance_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='roll_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
