# Generated by Django 5.1.6 on 2025-03-23 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_students_roll_no'),
    ]

    operations = [
    ]
