# Generated by Django 5.1.6 on 2025-03-23 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20250323_1236'),
    ]

    operations = [
    ]
