# Generated by Django 5.1.6 on 2025-03-30 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20250323_1240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
