# Generated by Django 5.1.6 on 2025-04-08 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.classes'),
        ),
    ]
