# Generated by Django 5.1.6 on 2025-04-08 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_studentevaluation_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentevaluation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.students'),
        ),
    ]
