# Generated by Django 5.1.6 on 2025-04-08 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_alter_quizresponse_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestions',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.quizzes'),
        ),
    ]
