# Generated by Django 5.1.6 on 2025-04-08 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_alter_studymaterials_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.classes'),
        ),
    ]
