# Generated by Django 5.1.6 on 2025-05-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_alter_announcements_class_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='parents',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
